name: QA Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa-pipeline:
    name: QA Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer
          extensions: sqlite3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run security check
        run: composer audit --locked

      - name: Run linter
        run: vendor/bin/php-cs-fixer fix src --dry-run --diff --using-cache=no

      - name: Run static-analysis
        run: vendor/bin/phpstan analyse src

      - name: Run test suite
        run: vendor/bin/phpunit --colors=always
